import { SHOWCASE_REPOS, type ShowcaseRepo } from "@/lib/showcase";

interface RepoCard extends ShowcaseRepo {
  liveStars: number | null;
}

async function fetchLiveStars(repo: ShowcaseRepo): Promise<number | null> {
  try {
    const res = await fetch(`https://api.github.com/repos/${repo.repo}`, {
      headers: { Accept: "application/vnd.github+json" },
      next: { revalidate: 60 * 60 * 6 },
    });
    if (!res.ok) return null;
    const data = (await res.json()) as { stargazers_count?: number };
    return typeof data.stargazers_count === "number" ? data.stargazers_count : null;
  } catch {
    return null;
  }
}

async function loadRepoCards(): Promise<RepoCard[]> {
  const live = await Promise.all(SHOWCASE_REPOS.map(fetchLiveStars));
  return SHOWCASE_REPOS.map((repo, index) => ({
    ...repo,
    liveStars: live[index],
  }));
}

function formatStars(value: number): string {
  if (value >= 1000) {
    const k = value / 1000;
    return `${k >= 100 ? Math.round(k) : k.toFixed(1)}k`;
  }
  return value.toString();
}

export async function SocialProof() {
  const repos = await loadRepoCards();
  const totalStars = repos.reduce(
    (sum, r) => sum + (r.liveStars ?? r.stars),
    0,
  );

  return (
    <section className="relative overflow-hidden py-32">
      <div className="mx-auto mb-16 max-w-2xl px-6 text-center">
        <div className="kicker">Real repos · real stars</div>
        <h2 className="mt-6 font-display text-3xl font-bold leading-tight tracking-tight text-bone sm:text-5xl">
          {formatStars(totalStars)}+ stars of open source, explained.
        </h2>
        <p className="mt-6 text-base text-fog">
          Every showcase video is generated by the same pipeline you'd run.
          No edits, no humans in the loop.
        </p>
      </div>

      <div className="mx-auto grid max-w-[1100px] grid-cols-2 gap-3 px-6 sm:grid-cols-4">
        {repos.map((repo) => (
          <a
            key={repo.slug}
            href={`/showcase/${repo.slug}`}
            data-cursor="interactive"
            className="surface-1 group relative flex items-center justify-between gap-3 rounded-2xl px-4 py-4 transition-all duration-400 ease-luxe hover:-translate-y-0.5 hover:border-electric/40"
          >
            <div className="min-w-0">
              <div className="truncate font-display text-base font-medium text-bone">
                {repo.repo.split("/")[1]}
              </div>
              <div className="truncate font-mono text-[10px] uppercase tracking-[0.32em] text-mist">
                {repo.language}
              </div>
            </div>
            <span className="shrink-0 rounded-full border border-white/10 bg-graphite/60 px-2.5 py-1 font-mono text-[11px] tabular-nums text-fog transition-colors duration-300 group-hover:border-electric/30 group-hover:text-electric">
              ★ {formatStars(repo.liveStars ?? repo.stars)}
            </span>
          </a>
        ))}
      </div>

      <figure className="mx-auto mt-20 max-w-2xl px-6">
        <blockquote className="surface-1 rounded-2xl p-8 text-center">
          <p className="font-display text-xl leading-snug text-bone sm:text-2xl">
            Day-1 beta. No fake quotes — try it and tell me what you think.
          </p>
          <figcaption className="mt-5 inline-flex items-center gap-3 text-sm">
            <span className="grid h-9 w-9 place-items-center rounded-full bg-electric/15 font-mono text-xs accent-electric">
              VS
            </span>
            <span className="text-left">
              <span className="block font-medium text-bone">Vineet Sista</span>
              <span className="block text-mist">Building Phantom · Columbus, Ohio</span>
            </span>
          </figcaption>
        </blockquote>
      </figure>
    </section>
  );
}
